#!/bin/sh
#
# nginx - this script starts and stops the nginx daemon
#
# chkconfig:   - 85 15
# description:  NGINX is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: nginx

nginx=/usr/local/nginx/sbin/nginx

case $1 in
    start)
        echo -n "Starting Nginx.."
        $nginx
        echo " done"
    ;;
    stop)
        echo -n "Stopping Nginx.."
        $nginx -s stop
        echo " done"
    ;;
    reload)
        echo -n "Reloading Nginx.."
        $nginx -s reload
        echo " done"
    ;;
    *)
        echo -n "Usage: $0 {start|stop|reload}"
    ;;
esac
